site_name: Documentação - Malha Fundiária Ambiental
site_author: Bernard Silva de Oliveira
theme:
  name: readthedocs
 
nav:
  - 'Home': 'index.md'
  - 'Ingestão de Dados': 'Ingestão de Dados.md'
  - 'Pré-processamento': 'Pré processamento dos dados.md'
  - 'Hierarquização': 'Hierarquização.md'
  - 'Conversão de estrutura Matricial': 'Conversão de estrutura Matricial.md'
  - 'Analise de sobreposição': 'Analise de sobreposição.md'
  - 'Integração Fundiária e Ambiental': 'Integração Fundiária e Ambiental.md'
  - 'Métricas de Avaliação': 'Métricas de Avaliação.md'
  - 'Visualização de Dados': 'Estatisticas.md' 

