site_name: Doc - Environmental Land Tenure
site_author: Bernard Silva de Oliveira
theme:
  name: material
 
nav:
  - 'Home': 'index.md'
  - 'Data Ingestion': 'Data Ingestion.md'
  - 'Data Preprocessing': 'Data Preprocessing.md'
  - 'Hierarchical of Land Tenure Layers': 'Hierarchy of Land Tenure Layers.md'
  - 'Layer Reclassification': 'Layer Reclassification.md'
  - 'Overlap Analysis': 'Overlap Analysis.md'
  - 'Environmental Integration': 'Environmental Integration.md'
  - 'Evaluation Metrics': 'Evaluation Metrics.md'
 

