site_name: Doc - Environmental Land Tenure
site_author: Bernard Silva de Oliveira

theme:
  name: material
  # Opcional: Ativa suporte a SPA e carregamento instantâneo caso queira performance de Big Data na doc
  features:
    - navigation.instant 

repo_name: LAPIG-UFG/Environmental-LandTenure 
repo_url: https://github.com/lapig-ufg/malha-fundiaria-ambiental

nav:
  - 'Home': 'index.md'
  - 'Data Ingestion': 'Data Ingestion.md'
  - 'Data Preprocessing': 'Data Preprocessing.md'
  - 'Hierarchical of Land Tenure Layers': 'Hierarchy of Land Tenure Layers.md'
  - 'Layer Reclassification': 'Layer Reclassification.md'
  - 'Overlap Analysis': 'Overlap Analysis.md'
  - 'Environmental Integration': 'Environmental Integration.md'
  - 'Evaluation Metrics': 'Evaluation Metrics.md'
  - 'Reference': 'Reference.md'

# CRUCIAL: Injeção dos scripts do MathJax para interpretar o Arithmatex
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
